bestor_content_helper.translations:
  type: config_object
  label: 'Bestor Nodes Helper translations'
  mapping:
    custom_translations:
      type: sequence
      label: 'Custom translations'
      sequence:
        type: mapping
        label: 'Translation entry'
        mapping:
          en:
            type: string
            label: 'English'
          fr:
            type: string
            label: 'French'
          nl:
            type: string
            label: 'Dutch'